runtime: nodejs20

automatic_scaling:
  max_instances: 20

handlers:
  - url: /.*
    script: auto
    secure: always
    http_headers:
      X-Content-Type-Options: nosniff
      X-Frame-Options: SAMEORIGIN
      Content-Security-Policy: "default-src * 'self' data: blob: https:; script-src * 'self' 'unsafe-inline'; style-src * 'self' 'unsafe-inline'; frame-ancestors 'self';"
      Cache-Control: no-store, must-revalidate
      Access-Control-Allow-Origin: "*"
      Access-Control-Allow-Methods: "GET, POST, OPTIONS"
      Access-Control-Allow-Headers: "Content-Type"
      Access-Control-Expose-Headers: "Content-Length, Content-Type"

# Environment variables should be set using Secret Manager
# DO NOT include secrets directly in this file 