runtime: nodejs20

instance_class: F2

automatic_scaling:
  max_instances: 20

handlers:
  - url: /.*
    script: auto
    secure: always
    http_headers:
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "SAMEORIGIN"
      Cache-Control: "no-store, must-revalidate"
      Access-Control-Allow-Origin: "*"
      Access-Control-Allow-Methods: "GET, POST, OPTIONS"
      Access-Control-Allow-Headers: "Content-Type"
      Access-Control-Expose-Headers: "Content-Length, Content-Type"

# Environment variables should be set using Secret Manager
# DO NOT include secrets directly in this file 
