/**
 * Google Cloud Platform App Engine configuration adapter
 * Manages app.yaml content and configuration for deployment
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '../../');
const appYamlPath = path.join(rootDir, 'app.yaml');

/**
 * App YAML configuration content
 */
export const appYamlContent = `# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# DO NOT EDIT THIS FILE DIRECTLY!
# This file is automatically generated at runtime.
# To modify app.yaml configuration, edit adapters/cloud/app-yaml.js instead.
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime: nodejs20

instance_class: F2

automatic_scaling:
  max_instances: 20

handlers:
  - url: /.*
    script: auto
    secure: always
    http_headers:
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "SAMEORIGIN"
      Cache-Control: "no-store, must-revalidate"
      Access-Control-Allow-Origin: "*"
      Access-Control-Allow-Methods: "GET, POST, OPTIONS"
      Access-Control-Allow-Headers: "Content-Type"
      Access-Control-Expose-Headers: "Content-Length, Content-Type"

# Environment variables should be set using Secret Manager
# DO NOT include secrets directly in this file 
`;

/**
 * Writes the app.yaml file to the root directory
 * Required by GCP App Engine deployment
 */
export function writeAppYaml() {
  try {
    fs.writeFileSync(appYamlPath, appYamlContent, 'utf8');
    return true;
  } catch (error) {
    console.error('[AppYaml] Error writing app.yaml:', error);
    return false;
  }
}

/**
 * Reads the current app.yaml file from the root directory
 */
export function readAppYaml() {
  try {
    return fs.readFileSync(appYamlPath, 'utf8');
  } catch (error) {
    return null;
  }
}

export const appYaml = {
  write: writeAppYaml,
  read: readAppYaml,
  content: appYamlContent
}; 